portal_cadastros/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('registros/', include('registros.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('', lambda request: redirect('registros/'))
]

registros/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.formulario_cadastro, name='formulario_cadastro'),
    path('listar_cadastros/', views.listar_cadastros, name='listar_cadastros'),
    path('visualizar_cadastro/<uuid:id>/', views.visualizar_cadastro, name='visualizar_cadastro'),
    path('visualizacao_kanban/', views.visualizacao_kanban, name='visualizacao_kanban'),
    path('atualizar_cadastro/<uuid:id>/', views.atualizar_cadastro, name='atualizar_cadastro'),
    path('disparar_emails/', views.disparar_emails, name='disparar_emails')
]

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

fornecedores/models.py
from django.db import models
from pessoas.models import Pessoa
import uuid

class SimNaoEnum(models.TextChoices):
    NAO = 'NAO', 'Não'
    SIM = 'SIM', 'Sim'

class AreaInteresse(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False,
                          unique=True)
    nome = models.CharField(max_length=120, unique=True)

    def __str__(self):
        return self.nome

# Create your models here.
class Fornecedor(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False,
                          unique=True)
    cnpj = models.CharField(max_length=18, null=True, blank=True)
    nome_empresarial = models.CharField(max_length=120, null=True, blank=True)
    tempo_mei = models.DateField(null=True, blank=True)
    possui_conta_pj = models.CharField(max_length=3, choices=SimNaoEnum.choices) # vinculada ao mei
    cnae_principal = models.CharField(max_length=255, null=True, blank=True)
    cnae_secundario = models.CharField(max_length=255, null=True, blank=True)
    prestou_servicos_mei = models.CharField(max_length=3, choices=SimNaoEnum.choices)
    servicos_prestados = models.TextField(null=True, blank=True)
    area_interesse = models.ManyToManyField(AreaInteresse)
    possui_disponibilidade_servicos_eventuais = models.CharField(max_length=3, choices=SimNaoEnum.choices)
    possui_smartphone = models.CharField(max_length=3, choices=SimNaoEnum.choices)
    atuou_em_laboratorio_analise_ambiental = models.CharField(max_length=3, choices=SimNaoEnum.choices)
    possui_cursos_area_ambiental = models.CharField(max_length=3, choices=SimNaoEnum.choices)
    cursos_realizados = models.CharField(max_length=255, null=True, blank=True)
    observacoes = models.TextField(null=True, blank=True)
    pessoa = models.OneToOneField(Pessoa, on_delete=models.CASCADE)

pessoas/models.py
from django.db import models
import uuid

class SimNaoEnum(models.TextChoices):
    NAO = 'NAO', 'Não'
    SIM = 'SIM', 'Sim'


# Create your models here.
class Pessoa(models.Model):
    class SituacaoEnum(models.TextChoices):
        PENDENTE = 'PENDENTE', 'Pendente'
        APROVADO = 'APROVADO', 'Aprovado'
        REPROVADO = 'REPROVADO', 'Reprovado'
        CONCLUIDO = 'CONCLUIDO', 'Concluído'

    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False,
                          unique=True)
    nome_completo = models.CharField(max_length=120)
    cpf = models.CharField(max_length=14)
    telefone = models.CharField(max_length=11)
    email = models.CharField(max_length=50)
    possui_veiculo = models.CharField(max_length=3, choices=SimNaoEnum.choices)
    situacao = models.CharField(max_length=50, choices=SituacaoEnum.choices, default=SituacaoEnum.PENDENTE)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    email_enviado = models.BooleanField(default=False)

# dados referente à localização
class Endereco(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False,
                          unique=True)
    cep = models.CharField(max_length=9)
    logradouro = models.CharField(max_length=120)
    numero = models.CharField(max_length=10)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    distancia_km = models.IntegerField(null=True, blank=True)
    distancia_tempo = models.CharField(max_length=255, null=True, blank=True)
    pessoa = models.OneToOneField(Pessoa, on_delete=models.CASCADE)

# dados formação
class FormacaoQualificacao(models.Model):
    class AreaFormacaoEnum(models.TextChoices):
        QUIMICA = 'QUIMICA', 'Química'
        BIOLOGIA = 'BIOLOGIA', 'Biologia'
        MEIO_AMBIENTE = 'MEIO_AMBIENTE', 'Meio Ambiente'
        LOGISTICA = 'LOGISTICA', 'Logística'
        COMERCIAL = 'COMERCIAL', 'Comercial'
        OUTROS = 'OUTROS', 'Outros'

    class GrauFormacaoEnum(models.TextChoices):
        ENSINO_MEDIO = 'ENSINO_MEDIO', 'Ensino Médio'
        TECNICO = 'TECNICO', 'Técnico'
        TECNOLOGO = 'TECNOLOGO', 'Tecnólogo'
        GRADUACAO = 'GRADUACAO', 'Graduação'
        POS_GRADUACAO = 'POS_GRADUACAO', 'Pós-Graduação'
        MESTRADO = 'MESTRADO', 'Mestrado'
        DOUTORADO = 'DOUTORADO', 'Doutorado'

    class RegistroConselhoClasseEnum(models.TextChoices):
        NAO_POSSUI = 'NAO_POSSUI', 'Não Possui'
        CRQ = 'CRQ', 'CRQ'
        CRBIO = 'CRBIO', 'CRBio'
        CREA = 'CREA', 'CREA'
        OUTRO = 'OUTRO', 'Outro'


    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False,
                          unique=True)
    area_formacao = models.CharField(max_length=35, choices=AreaFormacaoEnum.choices)
    text_formacao = models.CharField(null=True, blank=True)
    grau_formacao = models.CharField(max_length=30, choices=GrauFormacaoEnum.choices)
    possui_registro_conselho_classe = models.CharField(max_length=30, choices=RegistroConselhoClasseEnum.choices)
    numero_registro_conselho_classe = models.CharField(max_length=30, null=True, blank=True)
    registro_ativo_conselho_classe = models.CharField(max_length=3, choices=SimNaoEnum.choices)
    pessoa = models.OneToOneField(Pessoa, on_delete=models.CASCADE)

registros/models.py
from django.db import models

# Create your models here.

registros/views.py
from email import message
import email
from django.shortcuts import redirect, render, get_object_or_404
from fornecedores.forms import FornecedorForm
from pessoas.forms import PessoaForm
from pessoas.forms import EnderecoForm
from pessoas.forms import FormacaoQualificacaoForm
from django.contrib import messages
from django.contrib.messages import constants
from pessoas.models import Pessoa
from django.contrib.auth.decorators import login_required
from utils.enviar_email import enviar_email
from utils.enviar_email import TipoEmail
from utils.api_maps import obter_distancia

# Create your views here
def formulario_cadastro(request):
    if request.method == 'GET':
        fornecedor_form = FornecedorForm()
        pessoa_form = PessoaForm()
        endereco_form = EnderecoForm()
        formacao_form = FormacaoQualificacaoForm()
        context = {
            'fornecedor_form': fornecedor_form,
            'pessoa_form': pessoa_form,
            'endereco_form': endereco_form,
            'formacao_form': formacao_form,
        }
        return render(request, 'cadastro_fornecedor.html', context=context)
    else:
        pessoa_form = PessoaForm(request.POST)
        endereco_form = EnderecoForm(request.POST)
        fornecedor_form = FornecedorForm(request.POST)
        formacao_form = FormacaoQualificacaoForm(request.POST)
        # verificando se os formulários estão válidos
        if pessoa_form.is_valid() and endereco_form.is_valid() and fornecedor_form.is_valid() and formacao_form.is_valid():
            pessoa = pessoa_form.save()
            endereco = endereco_form.save(commit=False)
            fornecedor = fornecedor_form.save(commit=False)
            formacao = formacao_form.save(commit=False)
            endereco.pessoa = pessoa
            fornecedor.pessoa = pessoa
            formacao.pessoa = pessoa
            endereco.save()
            fornecedor.save()
            fornecedor_form.save_m2m()
            formacao.save()
            # limpando o formulário após salvar os dados
            pessoa_form = PessoaForm()
            endereco_form = EnderecoForm()
            fornecedor_form = FornecedorForm()
            formacao_form = FormacaoQualificacaoForm()
            context = {
                'pessoa_form': pessoa_form,
                'endereco_form': endereco_form,
                'fornecedor_form': fornecedor_form,
                'formacao_form': formacao_form
            }
            messages.add_message(request, constants.SUCCESS, 'Dados registrados com sucesso!')
            # definindo os dados para enviar o e-amil
            email_destinatario = pessoa.email
            tipo_email = TipoEmail.INSCRICAO
            nome_destinatario = pessoa.nome_completo
            enviar_email(tipo_email, email_destinatario, nome_destinatario)
            # definindo os dados de distância
            dados_distancia = obter_distancia(endereco.cep)
            if dados_distancia:
                distancia_km = dados_distancia.get('dados_distancia') / 1000 if dados_distancia.get('dados_distancia') else None
                distancia_tempo = dados_distancia.get('dados_tempo')
                endereco.distancia_km = distancia_km
                endereco.distancia_tempo = distancia_tempo
            # salvando os dados
            endereco.save()
            # redirecionando o usuário para a mesma página
            return redirect('/registros/')
        messages.add_message(request, constants.WARNING, 'Erro ao registrar os dados! Tente novamente.')
        return render(request, 'cadastro.html', context=context)


@login_required(login_url='/usuarios/login')
def listar_cadastros(request):
    avaliado = request.GET.get('enviado')
    if avaliado:
        if avaliado == 'true':
            avaliado = True
        else:
            avaliado = False
    if avaliado is None:
        cadastros = Pessoa.objects.all()
    else:    
        cadastros = Pessoa.objects.filter(email_enviado = avaliado)
    context = {
        'cadastros': cadastros
    }
    return render(request, 'listar_cadastros.html', context=context)


@login_required(login_url='/usuarios/login')
def visualizacao_kanban(request):
    pessoas_pendentes = Pessoa.objects.filter(situacao = Pessoa.SituacaoEnum.PENDENTE).filter(email_enviado = False)
    pessoas_aprovadas = Pessoa.objects.filter(situacao = Pessoa.SituacaoEnum.APROVADO).filter(email_enviado = False)
    pessoas_reprovadas = Pessoa.objects.filter(situacao = Pessoa.SituacaoEnum.REPROVADO).filter(email_enviado = False)
    pessoas_concluidas = Pessoa.objects.filter(email_enviado = True)
    context = {
        'pessoas_pendentes': pessoas_pendentes,
        'pessoas_aprovadas': pessoas_aprovadas,
        'pessoas_reprovadas': pessoas_reprovadas,
        'pessoas_concluidas': pessoas_concluidas
    }
    return render(request, 'visualizacao_kanban.html', context=context)


@login_required(login_url="/usuarios/login")
def visualizar_cadastro(request, id):
    pessoa = Pessoa.objects.get(id=id)
    context = {
        'pessoa': pessoa
    }
    return render(request, 'visualizar_cadastro.html', context=context)

@login_required(login_url="/usuarios/login")
def disparar_emails(request):
    # obtendo apenas as pessoas que estão com e-mail - false
    pessoas_pendentes = Pessoa.objects.filter(email_enviado = False)
    # disparando o e-mail para quem está com aprovado
    pessoas_aprovadas = pessoas_pendentes.filter(situacao = Pessoa.SituacaoEnum.APROVADO)
    pessoas_reprovadas = pessoas_pendentes.filter(situacao = Pessoa.SituacaoEnum.REPROVADO)

    # verificando se não existem pessoas classificadas
    if  not pessoas_aprovadas and not pessoas_reprovadas:
        messages.add_message(request, constants.WARNING, 'Não existem pessoas classificadas!')
        return redirect('/registros/listar_cadastros/?enviado=false')
    for pessoa in pessoas_aprovadas:
        # definindo os dados para enviar o e-amil
        email_destinatario = pessoa.email
        tipo_email = TipoEmail.CADASTRO_APROVADO
        nome_destinatario = pessoa.nome_completo
        # enviando o e-mail
        enviar_email(tipo_email, email_destinatario, nome_destinatario)
        # atualizando o cadastro para mostrar que foi disparado
        pessoa.email_enviado = True
        pessoa.save()
    # disparando o e-mail para quem está reprovado
    for pessoa in pessoas_reprovadas:
        # definindo os dados para enviar o e-amil
        email_destinatario = pessoa.email
        tipo_email = TipoEmail.CADASTRO_REPROVADO
        nome_destinatario = pessoa.nome_completo
        # enviando o e-mail
        enviar_email(tipo_email, email_destinatario, nome_destinatario)
        # atualizando o cadastro para mostrar que foi disparado
        pessoa.email_enviado = True
        pessoa.save()
    
    # retornando o usuário para a mesma página
    pessoas_aprovadas = pessoas_pendentes.filter(situacao = Pessoa.SituacaoEnum.REPROVADO)
    messages.add_message(request, constants.SUCCESS, 'E-mails enviados com sucesso!')
    
    return redirect('/registros/listar_cadastros/?enviado=false')

@login_required(login_url="/usuarios/login")
def atualizar_cadastro(request, id):
    pessoa = get_object_or_404(Pessoa, id=id)

    action = request.POST.get('action')

    if action == 'aprovar':
        pessoa.situacao = Pessoa.SituacaoEnum.APROVADO
        pessoa.save()
        messages.add_message(request, constants.SUCCESS, 'Cadastro aprovado com sucesso!')
        return redirect('/registros/listar_cadastros/?enviado=false')
    elif action == 'reprovar':
        pessoa.situacao = Pessoa.SituacaoEnum.REPROVADO
        pessoa.save()
        messages.add_message(request, constants.ERROR, 'Cadastro reprovado com sucesso!')
        return redirect('/registros/listar_cadastros/?enviado=false')
    else:
        messages.add_message(request, constants.ERROR, 'Erro ao atualizar cadastro!')
    return redirect('visualizar_cadastro', id=id)

registros/templates/listar_cadastros.html
{% extends 'base.html' %}
{% block title %}Listar Cadastros{% endblock %}

{% block content %}
<div class="container py-4">
  <h1 class="display-5 text-center mb-4">Lista de Cadastros</h1>

  <div class="d-flex align-items-center justify-content-between flex-wrap gap-3 mb-5">
    <div class="btn-group" role="group">
      <a class="btn btn-outline-primary {% if request.GET.enviado == 'true' %}active{% endif %}" href="{% url request.resolver_match.url_name %}?enviado=true">
        Avaliados
      </a>
      <a class="btn btn-outline-primary {% if request.GET.enviado == 'false' %}active{% endif %}" href="{% url request.resolver_match.url_name %}?enviado=false">
        Avaliar
      </a>
    </div>
    <form method="post" action="{% url 'disparar_emails' %}" style="display:inline;">
                {% csrf_token %} 
                {% if request.GET.enviado == 'false' %}
                  <button type="submit" class="btn btn-success">Enviar e-mails</button>
                {% endif %}
            </form>
  </div>

  <div class="table-responsive mt-3">
    <table class="table table-striped table-hover table-bordered align-middle">
      <thead>
        <tr class="text-center bg-light">
          <th scope="col">#</th>
          <th scope="col">Data Cadastro</th>
          <th scope="col">Nome Completo</th>
          <th scope="col">Telefone</th>
          <th scope="col">Bairro</th>
          <th scope="col">Cidade</th>
          <th scope="col">Situação</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for cadastro in cadastros %}
        <tr>
          <td class="text-center">{{ forloop.counter }}</td>
          <td>{{ cadastro.data_cadastro|date:"d/m/Y" }}</td>
          <td>{{ cadastro.nome_completo }}</td>
          <td>{{ cadastro.telefone }}</td>
          <td>{{ cadastro.endereco.bairro }}</td>
          <td>{{ cadastro.endereco.cidade }}</td>
          <td class="text-center">
            <span class="badge 
              {% if cadastro.situacao == 'PENDENTE' %}bg-warning text-dark
              {% elif cadastro.situacao == 'APROVADO' %}bg-success
              {% elif cadastro.situacao == 'REPROVADO' %}bg-danger
              {% else %}bg-secondary{% endif %}">
              {{ cadastro.get_situacao_display }}
            </span>
          </td>
          <td class="text-center">
            <a href="{% url 'visualizar_cadastro' cadastro.id %}" class="btn btn-sm btn-info">
              Visualizar
            </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="8" class="text-center text-muted py-4">Nenhum cadastro encontrado.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% if messages %}
                {% for message in messages %}
                    <div class="alert {{message.tags}} mt-4" role="alert">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
</div>
{% endblock %}

registros/templates/visualizar_cadastro.html
{% extends 'base.html' %}
{% block title %}Visualizar Cadastro{% endblock %}

{% block content %}
    <div class="container py-4"> 
        <h1 class="text-center mb-4">{{ pessoa.nome_completo }}</h1> 
        <p class="text-center text-muted lead mb-5">Detalhes completos do registro</p> 

        {# Grupo de Cards #}
        <div class="row g-4"> 

            {# Card: Dados Pessoais #}
            <div class="col-md-6">
                <div class="card shadow-sm h-100"> 
                    <div class="card-header bg-primary text-white">
                        <h4 class="mb-0">Informações Pessoais</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text mb-1"><strong>Data de Cadastro:</strong> {{ pessoa.data_cadastro|date:"d/m/Y" }}</p> {# Formata a data #}
                        <p class="card-text mb-1"><strong>CPF:</strong> {{ pessoa.cpf }}</p>    
                        <p class="card-text mb-1"><strong>Telefone:</strong> {{ pessoa.telefone }}</p>
                        <p class="card-text mb-1"><strong>E-mail:</strong> {{ pessoa.email }}</p>
                        <p class="card-text mb-1"><strong>Possui veículo:</strong> 
                            <span class="badge {% if pessoa.possui_veiculo == 'SIM' %}bg-success{% else %}bg-secondary{% endif %}">
                                {{ pessoa.get_possui_veiculo_display }}
                            </span>
                        </p>
                        <p class="card-text mb-0"><strong>Situação:</strong> 
                            <span class="badge {% if pessoa.situacao == 'PENDENTE' %}bg-warning text-dark{% elif pessoa.situacao == 'APROVADO' %}bg-success{% else %}bg-danger{% endif %}">
                                {{ pessoa.get_situacao_display }}
                            </span>
                        </p>
                    </div>
                </div>
            </div>

            {# Card: Endereço #}
            <div class="col-md-6">
                <div class="card shadow-sm h-100">
                    <div class="card-header bg-info text-white">
                        <h4 class="mb-0">Endereço</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text mb-1"><strong>CEP:</strong> {{ pessoa.endereco.cep }}</p>
                        <p class="card-text mb-1"><strong>Logradouro:</strong> {{ pessoa.endereco.logradouro }}</p>
                        <p class="card-text mb-1"><strong>Número:</strong> {{ pessoa.endereco.numero }}</p>
                        <p class="card-text mb-1"><strong>Bairro:</strong> {{ pessoa.endereco.bairro }}</p>
                        <p class="card-text mb-1"><strong>Cidade:</strong> {{ pessoa.endereco.cidade }}</p>
                        <p class="card-text mb-0"><strong>Estado:</strong> {{ pessoa.endereco.estado }}</p>
                        {% if pessoa.endereco.distancia_km %}
                        <p class="card-text mb-0"><strong>Distancia(km):</strong> {{ pessoa.endereco.distancia_km }}</p>
                        {% endif %}
                        {% if pessoa.endereco.distancia_tempo %}
                        <p class="card-text mb-0"><strong>Distância(min):</strong> {{ pessoa.endereco.distancia_tempo }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>

            {# Card: Formação e Qualificação #}
            <div class="col-md-12 mt-4">
                <div class="card shadow-sm">
                    <div class="card-header bg-dark text-white">
                        <h4 class="mb-0">Formação e Qualificação</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text mb-1"><strong>Área de Formação:</strong> {{ pessoa.formacaoqualificacao.get_area_formacao_display }}</p>
                        <p class="card-text mb-1"><strong>Texto Formação:</strong> 
                            {% if not pessoa.formacaoqualificacao.text_formacao %} 
                                <span class="text-muted">Campo não preenchido</span>
                            {% else %} 
                                {{ pessoa.formacaoqualificacao.text_formacao }}
                            {% endif %} 
                        </p>
                        <p class="card-text mb-1"><strong>Grau de Formação:</strong> {{ pessoa.formacaoqualificacao.get_grau_formacao_display }}</p>
                        <p class="card-text mb-1"><strong>Possui Registro de Conselho de Classe:</strong> {{ pessoa.formacaoqualificacao.get_possui_registro_conselho_classe_display }}</p>
                        <p class="card-text mb-1"><strong>Número do Registro:</strong> 
                            {% if not pessoa.formacaoqualificacao.numero_registro_conselho_classe %} 
                                <span class="text-muted">Campo não preenchido</span>
                            {% else %} 
                                {{ pessoa.formacaoqualificacao.numero_registro_conselho_classe }} 
                            {% endif %}
                        </p>
                        <p class="card-text mb-0"><strong>Registro ativo:</strong> 
                            <span class="badge {% if pessoa.formacaoqualificacao.registro_ativo_conselho_classe %}bg-success{% else %}bg-danger{% endif %}">
                                {% if pessoa.formacaoqualificacao.registro_ativo_conselho_classe %}Sim{% else %}Não{% endif %}
                            </span>
                        </p>
                    </div>
                </div>
            </div>

            {# Card: Detalhes do Fornecedor #}
            <div class="col-md-12 mt-4">
                <div class="card shadow-sm">
                    <div class="card-header bg-secondary text-white">
                        <h4 class="mb-0">Detalhes do Fornecedor</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text mb-1"><strong>CNPJ:</strong> {% if not pessoa.fornecedor.cnpj %} <span class="text-muted">Não informado</span> {% else %} {{ pessoa.fornecedor.cnpj }} {% endif %}</p>
                        <p class="card-text mb-1"><strong>Nome Empresarial:</strong> {% if not pessoa.fornecedor.nome_empresarial %} <span class="text-muted">Não informado</span> {% else %} {{ pessoa.fornecedor.nome_empresarial }} {% endif %}</p>
                        <p class="card-text mb-1"><strong>Data de cadastro do MEI:</strong> {% if not pessoa.fornecedor.tempo_mei %} <span class="text-muted">Não informado</span> {% else %} {{ pessoa.fornecedor.tempo_mei|date:"d/m/Y" }} {% endif %}</p>
                        <p class="card-text mb-1"><strong>Possui Conta PJ:</strong> 
                            <span class="badge {% if pessoa.fornecedor.possui_conta_pj == 'SIM' %}bg-success{% else %}bg-danger{% endif %}">
                                {{ pessoa.fornecedor.get_possui_conta_pj_display }}
                            </span>
                        </p>
                        <p class="card-text mb-1"><strong>CNAE Principal:</strong> {% if not pessoa.fornecedor.cnae_principal %} <span class="text-muted">Não informado</span> {% else %} {{ pessoa.fornecedor.cnae_principal }} {% endif %}</p>
                        <p class="card-text mb-1"><strong>CNAE Secundário:</strong> {% if not pessoa.fornecedor.cnae_secundario %} <span class="text-muted">Não informado</span> {% else %} {{ pessoa.fornecedor.cnae_secundario }} {% endif %}</p>
                        <p class="card-text mb-1"><strong>Prestou Serviços MEI:</strong> 
                            <span class="badge {% if pessoa.fornecedor.prestou_servicos_mei == 'SIM' %}bg-success{% else %}bg-danger{% endif %}">
                                {{ pessoa.fornecedor.get_prestou_servicos_mei_display }}
                            </span>
                        </p>
                        <p class="card-text mb-1"><strong>Serviços Prestados:</strong> {% if not pessoa.fornecedor.servicos_prestados %} <span class="text-muted">Não informado</span> {% else %} {{ pessoa.fornecedor.servicos_prestados }} {% endif %}</p>
                        
                        <p class="card-text mb-1"><strong>Área(s) de Interesse:</strong> 
                            {% if pessoa.fornecedor.area_interesse.all %}
                                <ul class="list-unstyled d-inline"> {# list-unstyled remove bullets, d-inline para ficar na mesma linha #}
                                    {% for area in pessoa.fornecedor.area_interesse.all %}
                                        <li class="badge bg-primary me-1 mb-1 d-inline-block">{{ area.nome }}</li> {# Um badge para cada item #}
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <span class="text-muted">Não informado</span>
                            {% endif %}
                        </p>
                        
                        <p class="card-text mb-1"><strong>Disponibilidade para Serviços Eventuais:</strong> 
                            <span class="badge {% if pessoa.fornecedor.possui_disponibilidade_servicos_eventuais == 'SIM' %}bg-success{% else %}bg-danger{% endif %}">
                                {{ pessoa.fornecedor.get_possui_disponibilidade_servicos_eventuais_display }}
                            </span>
                        </p>
                        <p class="card-text mb-1"><strong>Possui Smartphone:</strong> 
                            <span class="badge {% if pessoa.fornecedor.possui_smartphone == 'SIM' %}bg-success{% else %}bg-danger{% endif %}">
                                {{ pessoa.fornecedor.get_possui_smartphone_display }}
                            </span>
                        </p>
                        <p class="card-text mb-1"><strong>Atuou em laboratório de análises ambientais:</strong> 
                            <span class="badge {% if pessoa.fornecedor.atuou_em_laboratorio_analise_ambiental %}bg-success{% else %}bg-danger{% endif %}">
                                {% if pessoa.fornecedor.atuou_em_laboratorio_analise_ambiental %}Sim{% else %}Não{% endif %}
                            </span>
                        </p>
                        <p class="card-text mb-1"><strong>Cursos realizados:</strong> {% if not pessoa.fornecedor.cursos_realizados %} <span class="text-muted">Não informado</span> {% else %} {{ pessoa.fornecedor.cursos_realizados }} {% endif %}</p>
                        <p class="card-text mb-0"><strong>Observações:</strong> {% if not pessoa.fornecedor.observacoes %} <span class="text-muted">Não informado</span> {% else %} {{ pessoa.fornecedor.observacoes }} {% endif %}</p>
                    </div>
                </div>
            </div>

        </div> {# Fim da row #}
        
        {# Formulário único para Aprovar/Reprovar #}
        <div class="d-flex justify-content-center gap-5 pt-5">
            <form method="POST" action="{% url 'atualizar_cadastro' pessoa.id %}">
                {% csrf_token %}
                <input type="hidden" name="pessoa_id" value="{{ pessoa.id }}"> {# Adiciona o ID da pessoa como um campo oculto #}
                <button type="submit" name="action" value="aprovar" class="btn btn-primary">Aprovar</button>
                <button type="submit" name="action" value="reprovar" class="btn btn-warning">Reprovar</button>
            </form>
        </div>    

        {# Botão de Voltar #}
        <div class="text-center mt-5">
            <a href="{% url 'listar_cadastros' %}?enviado=false" class="btn btn-outline-secondary">Voltar para a Lista</a>
        </div>
         {% if messages %}
                {% for message in messages %}
                    <div class="alert {{message.tags}} mt-4" role="alert">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}

    </div>
{% endblock %}